import React, { useMemo, useRef } from 'react';
import * as THREE from 'three';
import { useFrame } from '@react-three/fiber';
import { Billboard, Text } from '@react-three/drei';

const DISTANCE_THRESHOLD = 50; // Fade out labels when camera is further than this from origin/label

const DistrictLabels = ({ blocks }) => {
    const labelsGroupRef = useRef();

    // Compute top 30 districts by file count
    // and find the highest building in that block for vertical offset
    const topDistricts = useMemo(() => {
        if (!blocks || blocks.length === 0) return [];

        // Sort blocks descending by file count inside the block
        const sortedBlocks = [...blocks].sort((a, b) => b.buildings.length - a.buildings.length);

        // Take top 30 out of performance and visual clutter constraints
        const top30 = sortedBlocks.slice(0, 30);

        return top30.map((block) => {
            // Find maximum building height to avoid placing text *inside* a building
            let maxHeight = 0;
            block.buildings.forEach(b => {
                if (b.height > maxHeight) maxHeight = b.height;
            });

            // Center of the block in world coordinates
            const centerX = block.worldX + block.blockWidth / 2;
            const centerZ = block.worldZ + block.blockDepth / 2;

            // Floating 4 units above the tallest building in this block
            const posY = maxHeight + 4.0;

            return {
                id: block.dirIndex,
                name: block.dir,
                position: [centerX, posY, centerZ],
                size: block.buildings.length
            };
        });
    }, [blocks]);

    // Handle fading based on camera distance to keep realistic look
    useFrame((state) => {
        if (!labelsGroupRef.current) return;

        const cameraPos = state.camera.position;

        // Iterate over all Billboard children (which contain the Text)
        labelsGroupRef.current.children.forEach((billboardObj) => {
            // Calculate distance from camera to this specific label
            const dist = cameraPos.distanceTo(billboardObj.position);

            // Simple linear fade: fully opaque under 25 units, fully transparent past DISTANCE_THRESHOLD
            const fadeStart = 25;
            const fadeRange = DISTANCE_THRESHOLD - fadeStart;

            let opacity = 1.0;
            if (dist > fadeStart) {
                opacity = 1.0 - (dist - fadeStart) / fadeRange;
            }
            if (opacity < 0) opacity = 0;
            if (opacity > 1) opacity = 1;

            // Apply opacity to the Text material
            // billboardObj.children[0] should be the Mesh generated by <Text>
            if (billboardObj.children.length > 0) {
                const textMesh = billboardObj.children[0];
                if (textMesh.material) {
                    textMesh.material.opacity = opacity;
                    textMesh.material.transparent = true;
                    // If opacity is practically 0, turn off rendering to save GPU
                    textMesh.visible = opacity > 0.05;
                }
            }
        });
    });

    if (topDistricts.length === 0) return null;

    return (
        <group ref={labelsGroupRef}>
            {topDistricts.map((district) => (
                <Billboard
                    key={`district-label-${district.id}`}
                    position={district.position}
                    follow={true}
                    lockX={false}
                    lockY={false}
                    lockZ={false}
                >
                    <Text
                        fontSize={1.2}
                        color="#ffffff"
                        outlineWidth={0.06}
                        outlineColor="#0f172a" // dark slate outline for contrast
                        anchorX="center"
                        anchorY="middle"
                    >
                        {district.name === 'root' ? '/' : district.name}
                    </Text>
                </Billboard>
            ))}
        </group>
    );
};

export default DistrictLabels;
